POST http://localhost:5000/api/technicians/register
Content-Type: application/json

{
   {
  "name": "Ravi Kumar",
  "phno": "9876543210",
  "mail": "ravi.kumar@example.com",
  "pass": "Ravi@123",
  "address": "Gulzar Houz, Hyderabad",
  "field": "Electrician",
  "aadhaarImage": "aadhaar_ravi.jpg",
  "experience": 8
  }
}

###
GET http://localhost:5000/api/technicians/register


###
POST http://localhost:5000/api/admin/accept-technician/688ce46af933c376c0506587

###
POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
  "uid": "abc123",
  "email": "example@email.com",
  "phone": "9876543210",
  "name": "John Doe",
  "role": "technician",
  "field": "electrical"
}

